local registry = require('mqActorNet.command_registry')
local state = require('mqActorNet.state')
local rexec = require('mqActorNet.rexec')

registry.bind('/anstop', state.stop)
registry.bind('/anexecute', rexec.sendDirectCommand)
registry.bind('/anaexecute', rexec.sendGlobalCommand)
registry.bind('/anaaexecute', rexec.sendSelfAndGlobalCommand)
registry.bind('/anzaexecute', rexec.sendSelfAndZoneCommand)
registry.bind('/anzexecute', rexec.sendZoneCommand)
registry.bind('/angaexecute', rexec.sendSelfAndGroupCommand)
registry.bind('/angexecute', rexec.sendGroupCommand)
registry.bind('/anraexecute', rexec.sendSelfAndRaidCommand)
registry.bind('/anrexecute', rexec.sendRaidCommand)